from . import oe_logistics
from . import oe_logistics_freight
from . import product
from . import sale_order
from . import wxapp_user
from . import wxapp_formid
from . import wxapp_config
from . import res_partner
from . import oe_score_logs
from . import oe_balance_logs
from . import wxapp_refund
from . import wxapp_msg_tpl
from . import wxapp_payment
from . import wxapp_product_tag
from . import wxapp_product_category
